import type { Token } from '../di/types.js';

/**
 * Operation trace for tracking individual operations
 */
export interface OperationTrace {
  label: string;
  traceId: string;
  startTime: number;
  endTime?: number;
  duration?: number;
  context?: Record<string, any>;
}

/**
 * Statistics for a specific route
 */
export interface RouteStats {
  path: string;
  count: number;
  totalTime: number;
  avgTime: number;
  minTime: number;
  maxTime: number;
  p99Time: number;
  totalMemory: number;
}

/**
 * Statistics for a specific provider
 */
export interface ProviderStats {
  token: Token;
  count: number;
  totalTime: number;
  avgTime: number;
  minTime: number;
  maxTime: number;
  slowestTime: number;
}

/**
 * Statistics for middleware execution
 */
export interface MiddlewareStats {
  name: string;
  count: number;
  totalTime: number;
  avgTime: number;
  minTime: number;
  maxTime: number;
}

/**
 * Garbage collection pause information
 */
export interface GCPause {
  timestamp: number;
  duration: number;
  type: string;
}

/**
 * Performance report generated by Layer 3
 */
export interface PerformanceReport {
  timestamp: number;
  duration: number;
  requestCount: number;
  slowestRoutes: RouteStats[];
  slowestProviders: ProviderStats[];
  slowestMiddleware: MiddlewareStats[];
  memoryUsage: number;
  gcPauses: GCPause[];
}

/**
 * Cached response data
 */
export interface CachedResponse {
  statusCode: number;
  headers: Record<string, string>;
  body: any;
  expiresAt: number;
}

/**
 * Middleware executor configuration
 */
export interface MiddlewareExecutor {
  type: 'guard' | 'pipe' | 'interceptor';
  name: string;
  executor: (context: any) => any | Promise<any>;
}

/**
 * HTTP method type
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS';

/**
 * Module metadata containing providers, imports, and exports
 */
export interface ModuleMetadata {
  providers?: unknown[];
  imports?: unknown[];
  exports?: unknown[];
  [key: string]: unknown;
}

/**
 * Route entry in the routing table
 */
export interface RouteEntry {
  method: HttpMethod;
  path: string;
  pattern: RegExp;
  paramNames: string[];
  handler: (context: any) => Promise<any>;
}

/**
 * Node in the route trie
 */
export interface TrieNode {
  children: Map<string, TrieNode>;
  handler?: (context: any) => Promise<any>;
  paramName?: string;
  isParam: boolean;
}

/**
 * Layer 1 configuration (Always-on metadata, routing, lazy loading)
 */
export interface Layer1Config {
  enabled: boolean;
}

/**
 * Layer 2 caching configuration
 */
export interface Layer2CachingConfig {
  enabled: boolean;
  ttl: number;
}

/**
 * Layer 2 dependency injection memoization configuration
 */
export interface Layer2DiConfig {
  memoization: boolean;
}

/**
 * Layer 2 memory pooling configuration
 */
export interface Layer2MemoryConfig {
  pooling: boolean;
  poolSize: number;
}

/**
 * Layer 2 configuration (Production caching, DI optimization, memory pooling)
 */
export interface Layer2Config {
  enabled: boolean;
  caching: Layer2CachingConfig;
  middlewareChain: boolean;
  di: Layer2DiConfig;
  memory: Layer2MemoryConfig;
}

/**
 * Layer 3 configuration (Observability and profiling)
 */
export interface Layer3Config {
  enabled: boolean;
  metricsPort: number;
  sampleSize: number;
}

/**
 * Complete optimization configuration
 */
export interface OptimizationConfig {
  layer1: Layer1Config;
  layer2: Layer2Config;
  layer3: Layer3Config;
}
